#!/bin/bash

# =======================================================================
# QUANTUM PI FORGE: MANUAL LIQUIDITY VERIFICATION SCRIPT
# January 29, 2026 - Sovereign Liquidity Audit
# =======================================================================
# This script helps verify the manual liquidity addition process
# and provides the exact parameters for the 0G Aristotle explorer
# =======================================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m'

# Sovereign Configuration
OINIO_TOKEN="0xbEbC1A40A18632CeE19D220647E7aD296A1A5F37"
DEX_ROUTER="0x0ff65f38fa43f0aac51901381acd7a8908ae2537"
DEX_FACTORY="0x307bFaA937768a073D41a2EbFBD952Be8E38BF91"
RPC_URL="https://16661.rpc.thirdweb.com"
EXPLORER_URL="https://chainscan.0g.ai"

# Liquidity Parameters (Manual Entry)
OINIO_AMOUNT="1000000000000000000000"    # 1,000 OINIO (18 decimals)
ETH_AMOUNT="50000000000000000000"       # 50 0G (18 decimals)
DEADLINE=$(( $(date +%s) + 1000 ))       # Current timestamp + 1000

# =======================================================================
# UTILITY FUNCTIONS
# =======================================================================

log() {
    echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')] $1${NC}"
}

info() {
    echo -e "${BLUE}[INFO] $1${NC}"
}

warning() {
    echo -e "${YELLOW}[WARNING] $1${NC}"
}

success() {
    echo -e "${PURPLE}[SUCCESS] $1${NC}"
}

# =======================================================================
# MANUAL INSTRUCTIONS
# =======================================================================

show_manual_instructions() {
    echo -e "${CYAN}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║         🏛️ MANUAL LIQUIDITY ADDITION INSTRUCTIONS            ║"
    echo "║              January 29, 2026 - Sovereign LP Creation        ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"

    echo ""
    echo "📋 STEP 1: APPROVE OINIO SPENDING"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "1. Go to: $EXPLORER_URL/address/$OINIO_TOKEN#writecontract"
    echo "2. Connect your wallet"
    echo "3. Find the 'approve' function"
    echo "4. Enter these exact parameters:"
    echo ""
    echo "   spender (address): $DEX_ROUTER"
    echo "   amount (uint256):  115792089237316195423570985008687907853269984665640564039457584007913129639935"
    echo "                      (This is type(uint256).max - unlimited approval)"
    echo ""
    echo "5. Click 'Write' and confirm the transaction"
    echo "6. Wait for confirmation..."
    echo ""

    echo "💧 STEP 2: ADD LIQUIDITY"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "1. Go to: $EXPLORER_URL/address/$DEX_ROUTER#writecontract"
    echo "2. Find the 'addLiquidityETH' function"
    echo "3. Enter these exact parameters:"
    echo ""
    echo "   token (address):           $OINIO_TOKEN"
    echo "   amountTokenDesired (uint): $OINIO_AMOUNT (1,000 OINIO)"
    echo "   amountTokenMin (uint):     0"
    echo "   amountETHMin (uint):       0"
    echo "   to (address):              [YOUR_WALLET_ADDRESS]"
    echo "   deadline (uint):           $DEADLINE"
    echo ""
    echo "4. Set 'Value (Payable Amount)' to: $ETH_AMOUNT (50 0G)"
    echo "5. Click 'Write' and confirm the transaction"
    echo "6. Wait for confirmation..."
    echo ""

    echo "🔍 STEP 3: VERIFY LIQUIDITY POOL"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "After both transactions confirm:"
    echo ""
    echo "1. Check your wallet for LP tokens"
    echo "2. Verify pool on DEX: $EXPLORER_URL/address/$DEX_FACTORY"
    echo "3. Test a small swap on the Sovereign Swap component"
    echo ""

    echo "⚡ TECHNICAL DETAILS"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "• Initial Price: 1 OINIO = 0.05 0G"
    echo "• Total Liquidity: 1,000 OINIO + 50 0G"
    echo "• LP Tokens: Minted to your address"
    echo "• Pool Address: Generated by factory contract"
    echo "• Trading Fee: 0.3% (DEX standard)"
    echo ""

    echo -e "${PURPLE}⚠️  IMPORTANT NOTES:${NC}"
    echo "• Ensure you have at least 1,000 OINIO + 50 0G + gas in your wallet"
    echo "• The deadline prevents stale transactions"
    echo "• LP tokens represent your share of the pool"
    echo "• You can remove liquidity later using 'removeLiquidityETH'"
    echo ""
}

# =======================================================================
# VERIFICATION FUNCTIONS
# =======================================================================

verify_contracts() {
    log "🔍 Verifying contract addresses on 0G Aristotle..."

    # Check if we can access the RPC
    if curl -s "$RPC_URL" > /dev/null; then
        info "✅ RPC endpoint accessible: $RPC_URL"
    else
        warning "❌ Cannot access RPC endpoint"
    fi

    # Check explorer accessibility
    if curl -s "$EXPLORER_URL" > /dev/null; then
        info "✅ Explorer accessible: $EXPLORER_URL"
    else
        warning "❌ Cannot access explorer"
    fi

    success "Contract verification complete"
}

# =======================================================================
# CALCULATION HELPERS
# =======================================================================

show_calculations() {
    echo ""
    echo "🧮 LIQUIDITY CALCULATIONS"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "OINIO Amount: 1,000 tokens"
    echo "0G Amount:    50 tokens"
    echo "Ratio:        1 OINIO = 0.05 0G"
    echo "Price:        1 0G = 20 OINIO"
    echo ""
    echo "Liquidity Math:"
    echo "• Total OINIO in pool: 1,000"
    echo "• Total 0G in pool:    50"
    echo "• K (constant product): 1,000 × 50 = 50,000"
    echo ""
    echo "Trading Impact:"
    echo "• Small trades (< 1% of pool): ~0.3% price impact"
    echo "• Medium trades (1-5%): 0.5-2% price impact"
    echo "• Large trades (>5%): Significant price impact"
    echo ""
}

# =======================================================================
# MAIN EXECUTION
# =======================================================================

main() {
    echo -e "${CYAN}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║     ⚡ QUANTUM PI FORGE: MANUAL LIQUIDITY SETUP GUIDE       ║"
    echo "║            January 29, 2026 - Sovereign LP Creation         ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"

    log "Starting manual liquidity setup guide..."

    # Show calculations
    show_calculations

    # Verify contracts
    verify_contracts

    # Show manual instructions
    show_manual_instructions

    echo -e "${PURPLE}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║                🎯 EXECUTION CHECKLIST                        ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"

    echo "□ Wallet connected to 0G Aristotle (Chain ID: 16661)"
    echo "□ Sufficient OINIO balance (≥ 1,000)"
    echo "□ Sufficient 0G balance (≥ 50 + gas)"
    echo "□ OINIO approval transaction submitted"
    echo "□ OINIO approval transaction confirmed"
    echo "□ addLiquidityETH transaction submitted"
    echo "□ addLiquidityETH transaction confirmed"
    echo "□ LP tokens received in wallet"
    echo "□ Test swap executed successfully"
    echo ""

    success "Manual setup guide complete!"
    success "Follow the steps above to ignite the sovereign liquidity pool"
    success "Once complete, the DEX will be live for all pioneers!"

    echo ""
    echo "🔗 Useful Links:"
    echo "• OINIO Token: $EXPLORER_URL/address/$OINIO_TOKEN"
    echo "• DEX Router: $EXPLORER_URL/address/$DEX_ROUTER"
    echo "• DEX Factory: $EXPLORER_URL/address/$DEX_FACTORY"
    echo "• Sovereign Swap: [Your deployed frontend URL]"
    echo ""
}

# =======================================================================
# SCRIPT ENTRY POINT
# =======================================================================

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --verify-only)
            verify_contracts
            exit 0
            ;;
        --calculations)
            show_calculations
            exit 0
            ;;
        --help)
            echo "Usage: $0 [options]"
            echo ""
            echo "Options:"
            echo "  --verify-only    Only verify contract accessibility"
            echo "  --calculations   Show liquidity calculations"
            echo "  --help          Show this help message"
            echo ""
            echo "Run without options to see the complete manual setup guide."
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            echo "Use --help for usage information."
            exit 1
            ;;
    esac
done

# Run main function
main "$@"