// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface UniswapV2Library$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "UniswapV2Library";
  readonly sourceName: "contracts/0g-uniswap-v2/src/libraries/UniswapV2Library.sol";
  readonly abi: [];
  readonly bytecode: "0x60566023600b82828239805160001a607314601657fe5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220bd7b71b6de5083ef27c6bb15f03ca54c5767e96d046ca227fe684c2b499fcb6464736f6c63430006060033";
  readonly deployedBytecode: "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220bd7b71b6de5083ef27c6bb15f03ca54c5767e96d046ca227fe684c2b499fcb6464736f6c63430006060033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/0g-uniswap-v2/src/libraries/UniswapV2Library.sol";
  readonly buildInfoId: "solc-0_6_6-a36df9ab03b9303ab2f695c4e804555a13d896cd";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["UniswapV2Library"]: UniswapV2Library$Type;
    ["contracts/0g-uniswap-v2/src/libraries/UniswapV2Library.sol:UniswapV2Library"]: UniswapV2Library$Type;
  }
}