#!/bin/bash
set -e

# Quantum Pi Forge — Cost Tracker
# Logs and aggregates GitHub Actions and infrastructure costs

COST_LOG_DIR=".agent/logs/costs"
mkdir -p "$COST_LOG_DIR"

TIMESTAMP=$(date -u +%Y-%m-%d)
WEEK=$(date +%V)
YEAR=$(date +%Y)

# Cost rates (as of Dec 2024)
GITHUB_ACTIONS_RATE=0.008  # $/min for Ubuntu runners
DATA_TRANSFER_RATE=0.01    # $/GB egress
STORAGE_RATE=0.023         # $/GB/month

log_cost_entry() {
  local service="$1"
  local unit="$2"
  local quantity="$3"
  local unit_cost="$4"
  local total_cost=$(echo "$quantity * $unit_cost" | bc)

  cat >> "$COST_LOG_DIR/week_$WEEK.csv" << EOF
$TIMESTAMP,$service,$unit,$quantity,$unit_cost,$total_cost
EOF

  echo "[COST] $service: $quantity $unit @ \$$unit_cost = \$$total_cost"
}

# Example: Log GitHub Actions compute cost
log_github_actions_cost() {
  local runtime_minutes="${1:-0}"
  if [ "$runtime_minutes" -gt 0 ]; then
    log_cost_entry "GitHub Actions" "minutes" "$runtime_minutes" "$GITHUB_ACTIONS_RATE"
  fi
}

# Example: Log data transfer cost
log_data_transfer_cost() {
  local data_gb="${1:-0}"
  if (( $(echo "$data_gb > 0" | bc -l) )); then
    log_cost_entry "Data Transfer" "GB" "$data_gb" "$DATA_TRANSFER_RATE"
  fi
}

# Generate weekly cost report
generate_weekly_cost_report() {
  local report_file="$COST_LOG_DIR/cost_report_week_$WEEK.md"

  if [ ! -f "$COST_LOG_DIR/week_$WEEK.csv" ]; then
    echo "[INFO] No cost data for week $WEEK"
    return
  fi

  local total_cost=$(awk -F',' 'NR>1 {sum+=$6} END {printf "%.2f", sum}' "$COST_LOG_DIR/week_$WEEK.csv")

  cat > "$report_file" << EOF
# Cost Report — Week $WEEK, $YEAR

**Report Generated:** $(date -u +%Y-%m-%dT%H:%M:%SZ)

## Summary

| Category | Cost |
|----------|------|
| Total Weekly Cost | \$$total_cost |
| Estimated Monthly Cost | \$$(echo "$total_cost * 4.33" | bc) |
| Estimated Annual Cost | \$$(echo "$total_cost * 52" | bc) |

## Detailed Breakdown

\`\`\`csv
$(cat "$COST_LOG_DIR/week_$WEEK.csv")
\`\`\`

## Optimization Recommendations

1. **Consolidate Workflows:** Reduce parallel runs (save ~25%)
2. **Cache Dependencies:** npm cache cuts runtime by 2-3 min
3. **Use Spot Instances:** For non-critical jobs (save ~70%)
4. **Archive Old Logs:** Compress logs >30 days old (save ~40%)

---

*Generated by Quantum Pi Forge Cost Tracker*
EOF

  echo "[COST] Report saved to $report_file"
  cat "$report_file"
}

# Export functions
export -f log_cost_entry
export -f log_github_actions_cost
export -f log_data_transfer_cost
export -f generate_weekly_cost_report
