// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface TransferHelper$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "TransferHelper";
  readonly sourceName: "contracts/0g-uniswap-v2/src/libraries/TransferHelper.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220111cd87ddf9944a428ba22e27d113c5c9d4a2a1719117a8302f484a6d9408ce664736f6c63430008180033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220111cd87ddf9944a428ba22e27d113c5c9d4a2a1719117a8302f484a6d9408ce664736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/0g-uniswap-v2/src/libraries/TransferHelper.sol";
  readonly buildInfoId: "solc-0_8_24-2fe1d8c6e7b45055dc308041115240ebf6853dc4";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["TransferHelper"]: TransferHelper$Type;
    ["contracts/0g-uniswap-v2/src/libraries/TransferHelper.sol:TransferHelper"]: TransferHelper$Type;
  }
}