// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IWETH$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IWETH";
  readonly sourceName: "contracts/0g-uniswap-v2/src/interfaces/IWETH.sol";
  readonly abi: [{"inputs":[],"name":"deposit","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"value","type":"uint256"}],"name":"transfer","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"withdraw","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/0g-uniswap-v2/src/interfaces/IWETH.sol";
  readonly buildInfoId: "solc-0_8_20-8197378ab970add4fd86455bc3ca3a37f891afb8";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IWETH"]: IWETH$Type;
    ["contracts/0g-uniswap-v2/src/interfaces/IWETH.sol:IWETH"]: IWETH$Type;
  }
}