// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface SafeMath$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "SafeMath";
  readonly sourceName: "contracts/0g-uniswap-v2/src/libraries/SafeMath.sol";
  readonly abi: [];
  readonly bytecode: "0x60566023600b82828239805160001a607314601657fe5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220f6378e43dcac627b9f71ab86565e7e4bb7b653ab1ec07599d0e6cd11c530ae3d64736f6c63430006060033";
  readonly deployedBytecode: "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220f6378e43dcac627b9f71ab86565e7e4bb7b653ab1ec07599d0e6cd11c530ae3d64736f6c63430006060033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/0g-uniswap-v2/src/libraries/SafeMath.sol";
  readonly buildInfoId: "solc-0_6_6-6edb373f2679ea75424ce678220e3e6365f1a871";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["SafeMath"]: SafeMath$Type;
    ["contracts/0g-uniswap-v2/src/libraries/SafeMath.sol:SafeMath"]: SafeMath$Type;
  }
}