// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface SafeMath$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "SafeMath";
  readonly sourceName: "contracts/0g-uniswap-v2/src/libraries/SafeMathUniswap.sol";
  readonly abi: [];
  readonly bytecode: "0x60556023600b82828239805160001a607314601657fe5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea265627a7a723158203056f8014dafecab8286b3294104613c288b73ac5e1f568151884058aa985b6064736f6c63430005100032";
  readonly deployedBytecode: "0x73000000000000000000000000000000000000000030146080604052600080fdfea265627a7a723158203056f8014dafecab8286b3294104613c288b73ac5e1f568151884058aa985b6064736f6c63430005100032";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/0g-uniswap-v2/src/libraries/SafeMathUniswap.sol";
  readonly buildInfoId: "solc-0_5_16-c1d937802f66489de19bb3718363c58554af4848";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["SafeMath"]: SafeMath$Type;
    ["contracts/0g-uniswap-v2/src/libraries/SafeMathUniswap.sol:SafeMath"]: SafeMath$Type;
  }
}